##
# Backend Blog
##
-
  name: 'Page action with arguments'
  uriPattern: 'backend/{page}/{@action}'
  defaults:
    '@controller': 'Backend'
  routeParts:
    backend:
      objectType: 'Flow\Box\Domain\Model\Page'
      uriPattern: '{title}'

-
  name: 'Fallback action'
  uriPattern: 'backend(/{@action})'
  defaults:
    '@controller': 'Backend'
    '@action':     'index'

##
# Blog of Page
##
-
  name: 'Page action with arguments'
  uriPattern: 'pages/{page}/{@action}'
  defaults:
    '@controller': 'Page'
  routeParts:
    page:
      objectType: 'Flow\Box\Domain\Model\Page'
      uriPattern: '{title}'

-
  name: 'Page actions'
  uriPattern:    'pages/{@action}'
  defaults:
    '@controller': 'Page'

-
  name: 'Fallback action'
  uriPattern: '(pages)'
  defaults:
    '@controller': 'Page'
    '@action':     'index'

##
# Blog of Account
##
-
  name: 'Acount action with arguments'
  uriPattern: 'accounts/{account}/{@action}'
  defaults:
    '@controller': 'Account'

-
  name: 'Account actions'
  uriPattern:    'accouts(/{@action})'
  defaults:
    '@controller': 'Account'