-
  name: 'Flow.Box Routes'
  uriPattern: '{@controller}(/{@action})'
  defaults:
    '@package':    'Flow.Box'
    '@controller': ''
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: TRUE

##
# Backend Blog
##
-
  name: 'Backend action with arguments'
  uriPattern: 'backend/{@controller}(/{@action})'
  defaults:
    '@controller': 'Backend'
  routeParts:
    backend:
      objectType: 'Flow\Box\Domain\Model\Page'
      uriPattern: '{title}'

##
# Blog of Page
##
-
  name: 'Page action with arguments'
  uriPattern: 'pages/{page}/{@action}'
  defaults:
    '@controller': 'Page'
  routeParts:
    page:
      objectType: 'Flow\Box\Domain\Model\Page'
      uriPattern: '{title}'


##
# Blog of Account
##
-
  name: 'Acount action with arguments'
  uriPattern: 'accounts/{account}/{@action}'
  defaults:
    '@controller': 'Account'

-
  name: 'fallback'
  uriPattern: ''
  defaults:
    '@package':    'Flow.Box'
    '@controller': 'Seed'
    '@action':     'index'
    '@format':     'html'
