##
# Blog of Page
##
-
  name: 'Page action with arguments'
  uriPattern: 'pages/{page}/{@action}'
  defaults:
    '@controller': 'Page'
  routeParts:
    page:
      objectType: 'Flow\Box\Domain\Model\Page'
      uriPattern: '{title}'


##
# Blog of Account
##
-
  name: 'Acount action with arguments'
  uriPattern: 'backend/{@controller}/{account}(/{@action})'
  defaults:
    '@subpackage': 'Backend'
    '@controller': 'Account'

##
# Backend Blog
##
-
  name: 'Backend action with arguments'
  uriPattern: 'backend/{@controller}(/{@action})'
  defaults:
    '@subpackage': 'Backend'
    '@controller': 'Dashboard'
    '@action': 'index'
    '@format':     'html'
  appendExceedingArguments: TRUE

-
  name: 'Backend Login'
  uriPattern: 'backend'
  defaults:
    '@package':    'Flow.Box'
    '@subpackage': 'Backend'
    '@controller': 'Login'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: TRUE

-
  name: 'Flow.Box Routes'
  uriPattern: '{@controller}(/{@action})'
  defaults:
    '@package':    'Flow.Box'
    '@controller': ''
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: TRUE


-
  name: 'fallback'
  uriPattern: ''
  defaults:
    '@package':    'Flow.Box'
    '@controller': 'Page'
    '@action':     'index'
    '@format':     'html'
