-
  name: 'Home page'
  uriPattern: ''
  defaults:
    '@package':    'Flow.Box'
    '@controller': 'Page'
    '@action':     'index'
    '@format':     'html'
    language: 'km'

-
  name: 'Backend Login'
  uriPattern: 'backend'
  defaults:
    '@package':    'Flow.Box'
    '@subpackage': 'Backend'
    '@controller': 'Login'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: TRUE

-
  name: 'Backend all actions'
  uriPattern: 'backend/{@controller}(/{@action})'
  defaults:
    '@subpackage': 'Backend'
    '@controller': 'Dashboard'
    '@action': 'index'
    '@format':     'html'
  appendExceedingArguments: TRUE

-
  name: 'FE all action with langauage'
  uriPattern: '{language}/{@action}'
  defaults:
    '@package':    'Flow.Box'
    '@controller': 'Page'
    '@format':     'html'
    language: 'km'
  appendExceedingArguments: TRUE
